#!/usr/bin/env python3
"""Y7 P01 — sample spaces, assigning probabilities, predicting how many times an outcome might occur."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))
from _build_lib_y7 import build, cl

ROOT = Path("/Users/jirrahmacarthur/Claude Cowork access/Kulin Nation Curriculum")
SK = ROOT / "questions/level-07/Mathematics/VC2M7P01.skeleton.json"
OUT = ROOT / "questions/level-07/Mathematics/VC2M7P01.json"

TF_L2 = [
    ("A sample space is the set of all possible outcomes of an experiment.", True, "Sample space = all outcomes."),
    ("Tossing a coin has a sample space of two: heads and tails.", True, "Coin = {H, T}."),
    ("Rolling a six-sided die has a sample space of six.", True, "Die = {1,2,3,4,5,6}."),
    ("Probability of an outcome is between 0 and 1 inclusive.", True, "0 ≤ P ≤ 1."),
    ("If outcomes are equally likely, P = 1/total outcomes.", True, "Equal likely: 1/n."),
    ("A sample space includes only one outcome.", False, "It includes all outcomes."),
    ("Tossing a coin has a sample space of one.", False, "It has two."),
    ("Rolling a six-sided die has a sample space of one.", False, "It has six."),
    ("Probability of an outcome can be greater than 1.", False, "Max is 1."),
    ("If outcomes are equally likely, P = 0 for every outcome.", False, "P = 1/n, not 0."),
    ("Probability 0 means the event is certain to happen.", False, "P = 0 is impossible, not certain."),
    ("Probability 1 means the event will never happen.", False, "P = 1 is certain, not impossible."),
]
TF_L3 = [
    ("If P(heads) = 0.5, in 100 tosses we expect about 50 heads.", True, "100 × 0.5 = 50."),
    ("Rolling a 4 on a fair die has probability 1/6.", True, "1/6 for any face."),
    ("In 60 rolls of a fair die, we expect each face about 10 times.", True, "60 × 1/6 = 10."),
    ("If P(heads) = 0.5, in 100 tosses we expect about 100 heads.", False, "Expect 50."),
    ("Rolling a 4 on a fair die has probability 1/2.", False, "1/6, not 1/2."),
    ("In 60 rolls of a die, we expect each face about 60 times.", False, "About 10 each."),
    ("Equally likely outcomes have different probabilities each in this case.", False, "Equal outcomes share P."),
    ("Predictions from probability are always exactly correct.", False, "They are approximate."),
]
TF_L4 = [
    ("Sample spaces, probabilities, and predictions help us reason about chance experiments.", True, "Three key chance ideas."),
    ("Probability has no use in real-world prediction.", False, "Used widely."),
]

MC_L2 = [
    ("What is a sample space?",
     "The set of all possible outcomes of an experiment today",
     "Sample space = all outcomes.",
     ["The set of only the most likely outcomes today", "The set of impossible outcomes only today"]),
    ("What is the sample space for tossing a coin?",
     "Heads and tails are the two possible outcomes today",
     "Coin = {H, T}.",
     ["Only heads is the outcome today", "Heads, tails, and edge are the outcomes today"]),
    ("What is the sample space for rolling a six-sided die?",
     "The numbers one through six are the six possible outcomes today",
     "Die = {1,2,3,4,5,6}.",
     ["Only one and six are the outcomes today", "The numbers one through twelve are outcomes today"]),
    ("What is the range of probability values?",
     "Between zero and one inclusive on the number line today",
     "0 ≤ P ≤ 1.",
     ["Between zero and one hundred inclusive today", "Between negative one and one inclusive today"]),
    ("What is the probability of each outcome if equally likely?",
     "One divided by the total number of outcomes today",
     "P = 1/n.",
     ["Zero for every equally likely outcome today", "Total outcomes divided by one today"]),
    ("What does probability of 0 mean?",
     "The event is impossible and will never happen today",
     "P = 0: impossible.",
     ["The event is certain to happen today", "The event has equal chance of happening today"]),
    ("What does probability of 1 mean?",
     "The event is certain to happen today",
     "P = 1: certain.",
     ["The event is impossible and will never happen today", "The event has equal chance of happening today"]),
    ("If P(heads) = 0.5, how many heads do we expect in 100 tosses?",
     "About fifty heads in one hundred tosses today",
     "Expect ~50 heads.",
     ["About one hundred heads in one hundred tosses today", "About zero heads in one hundred tosses today"]),
    ("What is the probability of rolling a 4 on a fair die?",
     "One out of six, since each face is equally likely today",
     "P = 1/6.",
     ["One out of two, since 4 is one number today", "Zero, since 4 cannot occur today"]),
    ("In 60 rolls of a fair die, how many of each face do we expect?",
     "About ten of each face, since 60 ÷ 6 = 10 today",
     "~10 each.",
     ["About sixty of each face today", "About one of each face today"]),
    ("Are equally likely outcomes the same probability each?",
     "Yes, each equally likely outcome has the same probability today",
     "Equal P each.",
     ["No, equally likely outcomes have different probabilities today", "Only some equally likely outcomes share probability today"]),
    ("Are probability predictions always exactly correct?",
     "No, predictions are approximate, not exact today",
     "Approximate predictions.",
     ["Yes, predictions are always exactly correct today", "Only when the experiment is small are predictions exact today"]),
]
MC_L3 = [
    ("Why is identifying the sample space the first step?",
     "Knowing all possible outcomes lets us assign probabilities correctly today",
     "Sample space sets up probability.",
     ["Sample space is unimportant in probability today", "We can assign probability without sample space today"]),
    ("Why does P(heads) = 1/2 for a fair coin?",
     "Two equally likely outcomes mean each has probability 1/2 today",
     "Two equally likely outcomes.",
     ["The coin has only one possible outcome today", "Heads is more likely than tails always today"]),
    ("Why does each die face have P = 1/6?",
     "Six equally likely outcomes mean each has probability 1/6 today",
     "Six equally likely outcomes.",
     ["Each face has P = 1/2 always today", "Some faces have higher probability than others today"]),
    ("Why is probability bounded by 0 and 1?",
     "0 means impossible, 1 means certain; nothing falls outside this range today",
     "0 to 1 covers all chance.",
     ["Probability can range up to 100 today", "Probability has no upper bound today"]),
    ("Why does 100 tosses with P = 0.5 give ~50 heads?",
     "Multiplying probability by trials gives the expected count today",
     "Expected = P × trials.",
     ["Multiplying probability by trials gives 100 today", "Probability is unrelated to expected count today"]),
    ("Why are predictions approximate not exact?",
     "Real experiments include random variation around expected values today",
     "Random variation.",
     ["Predictions are always exactly correct today", "Predictions only work for small experiments today"]),
    ("Why is P = 0 the same as impossible?",
     "There is no chance the outcome will occur in the experiment today",
     "Zero chance = impossible.",
     ["P = 0 means equal chance always today", "P = 0 means certain to happen today"]),
    ("Why is P = 1 the same as certain?",
     "The outcome is guaranteed to occur in every trial today",
     "P = 1: certain.",
     ["P = 1 means impossible always today", "P = 1 means equal chance always today"]),
    ("Why is sample space useful for probability calculations?",
     "It lists every possible outcome to count favourable ones today",
     "List outcomes to count.",
     ["Sample space hides outcomes from probability today", "Sample space is unrelated to probability today"]),
    ("Why does 60 rolls give ~10 of each face?",
     "Sixty divided by six gives ten as the expected count for each today",
     "60 ÷ 6 = 10.",
     ["Sixty rolls give about sixty of each face today", "Sixty rolls give about one of each face today"]),
    ("Why are equally likely outcomes a useful idealisation?",
     "Many simple experiments approximate equally likely outcomes well today",
     "Idealisation works in practice.",
     ["Equally likely outcomes never occur in practice today", "Equally likely outcomes always occur exactly today"]),
    ("Why are probabilities sometimes given as fractions?",
     "Fractions like 1/6 show the exact ratio of favourable to total outcomes today",
     "Fractions show ratios.",
     ["Fractions hide the probability today", "Probabilities are never given as fractions today"]),
]
MC_L4 = [
    ("Which best explains sample spaces and probability?",
     "Sample spaces, probabilities, and predictions help us reason about chance today",
     "Three key chance ideas.",
     ["Probability has no use in chance experiments today", "Sample spaces are unrelated to probability today"]),
    ("Why is identifying the sample space first?",
     "Knowing all possible outcomes lets us assign probabilities correctly today",
     "Sample space sets up probability.",
     ["Sample space is unimportant today", "Probability needs no sample space today"]),
    ("Why does P(heads) = 1/2 for a fair coin?",
     "Two equally likely outcomes mean each has probability 1/2 today",
     "Two equally likely outcomes.",
     ["The coin has only one outcome today", "Heads is more likely than tails today"]),
    ("Why does each die face have P = 1/6?",
     "Six equally likely outcomes mean each has probability 1/6 today",
     "Six equally likely outcomes.",
     ["Each face has P = 1/2 today", "Some faces have higher probability today"]),
    ("Why is probability bounded by 0 and 1?",
     "0 means impossible, 1 means certain; nothing falls outside this range today",
     "0 to 1 covers all chance.",
     ["Probability can range up to 100 today", "Probability has no upper bound today"]),
    ("Why does 100 tosses with P = 0.5 give ~50 heads?",
     "Multiplying probability by trials gives the expected count today",
     "Expected = P × trials.",
     ["Multiplying probability by trials gives 100 today", "Probability is unrelated to expected count today"]),
    ("Why are predictions approximate not exact?",
     "Real experiments include random variation around expected values today",
     "Random variation.",
     ["Predictions are always exactly correct today", "Predictions only work for small experiments today"]),
    ("Why is P = 0 the same as impossible?",
     "There is no chance the outcome will occur in the experiment today",
     "Zero chance = impossible.",
     ["P = 0 means equal chance today", "P = 0 means certain today"]),
    ("Why is P = 1 the same as certain?",
     "The outcome is guaranteed to occur in every trial today",
     "P = 1: certain.",
     ["P = 1 means impossible today", "P = 1 means equal chance today"]),
    ("Why does 60 rolls give ~10 of each face?",
     "Sixty divided by six gives ten as the expected count for each today",
     "60 ÷ 6 = 10.",
     ["Sixty rolls give about sixty of each face today", "Sixty rolls give about one of each face today"]),
    ("Why are equally likely outcomes a useful model?",
     "Many simple experiments approximate equally likely outcomes well today",
     "Idealisation works in practice.",
     ["Equally likely outcomes never occur today", "Equally likely outcomes always occur exactly today"]),
    ("Why are probabilities sometimes given as fractions?",
     "Fractions like 1/6 show the exact ratio of favourable to total outcomes today",
     "Fractions show ratios.",
     ["Fractions hide the probability today", "Probabilities are never given as fractions today"]),
]
MC_L5 = [
    ("Evaluate: how do sample spaces and probability work together?",
     "Sample spaces, probabilities, and predictions help us reason about chance today",
     "Three key chance ideas.",
     ["Probability has no use today", "Sample spaces are unrelated today"]),
    ("Justify: why is identifying the sample space first?",
     "Knowing all possible outcomes lets us assign probabilities correctly today",
     "Sample space sets up probability.",
     ["Sample space is unimportant today", "Probability needs no sample space today"]),
    ("Assess: when does P(heads) = 1/2 hold for a coin?",
     "When the coin is fair and has two equally likely outcomes today",
     "Fair coin: 2 equally likely.",
     ["When the coin always lands on heads today", "When the coin has only one possible outcome today"]),
    ("Critique: a risk of treating probability above 1 as valid is what?",
     "Probability is bounded by 0 and 1; values above 1 are impossible today",
     "0 to 1 only.",
     ["Probability has no upper bound today", "Probability up to 100 is fine today"]),
    ("Evaluate: how does Expected = P × trials work?",
     "Multiplying probability by trials gives the expected count today",
     "Expected = P × trials.",
     ["Multiplying gives the trial count always today", "Probability is unrelated to expected count today"]),
    ("Justify: why are predictions approximate?",
     "Real experiments include random variation around expected values today",
     "Random variation.",
     ["Predictions are always exactly correct today", "Predictions only work for small experiments today"]),
    ("Assess: when does P = 0 best capture impossibility?",
     "When there is truly no chance the outcome will occur today",
     "Zero chance = impossible.",
     ["P = 0 means equal chance today", "P = 0 means certain today"]),
    ("Critique: a risk of confusing P = 1 with possible is what?",
     "P = 1 means certain, not just possible; all probability of 1 means it will happen today",
     "P = 1: certain, not just possible.",
     ["P = 1 means possible only today", "P = 1 means impossible today"]),
    ("Evaluate: how does 60 rolls give ~10 each face?",
     "Sixty divided by six gives ten as the expected count today",
     "60 ÷ 6 = 10.",
     ["Sixty gives about sixty of each face today", "Sixty gives about one of each face today"]),
    ("Justify: why are equally likely outcomes a useful model?",
     "Many simple experiments approximate equally likely outcomes well today",
     "Idealisation works in practice.",
     ["Equally likely outcomes never occur today", "Equally likely outcomes always occur exactly today"]),
    ("Assess: when do fractions best express probabilities?",
     "When the exact ratio of favourable to total outcomes is needed today",
     "Fractions show ratios.",
     ["When the probability is to be hidden today", "When the experiment is too complex today"]),
    ("Critique: a risk of expecting exactly 50 heads in 100 tosses is what?",
     "Real experiments vary; 50 is the expected count, not the guaranteed outcome today",
     "Expected ≠ guaranteed.",
     ["100 tosses always give exactly 50 heads today", "Random variation never affects the outcome today"]),
    ("Evaluate: how do First Nations games use chance ideas?",
     "Many traditional games involve chance with equally likely outcomes today",
     "Games use chance.",
     ["First Nations games never involve chance today", "Chance is only a modern idea today"]),
    ("Justify: why does sample space underpin probability?",
     "Listing all outcomes lets us count favourable ones for probability today",
     "List outcomes to count.",
     ["Sample space is unrelated to probability today", "Probability needs no sample space today"]),
]
CL_L2 = [
    cl("A sample space is the set of all possible outcomes of an {{blank:1}} for the {{blank:2}}.", "experiment", "country"),
    cl("Tossing a coin has a sample space of two: heads and {{blank:1}} for the {{blank:2}}.", "tails", "country"),
]
CL_L3 = [
    cl("Rolling a six-sided die has a sample space of {{blank:1}} for the {{blank:2}}.", "six", "country"),
    cl("Probability of an outcome is between 0 and {{blank:1}} inclusive for the {{blank:2}}.", "1", "country"),
    cl("If outcomes are equally likely, P = 1/total {{blank:1}} for the {{blank:2}}.", "outcomes", "country"),
    cl("If P(heads) = 0.5, in 100 tosses we expect about {{blank:1}} heads for the {{blank:2}}.", "50", "country"),
    cl("Rolling a 4 on a fair die has probability 1/{{blank:1}} for the {{blank:2}}.", "6", "country"),
    cl("In 60 rolls of a fair die, we expect each face about {{blank:1}} times for the {{blank:2}}.", "10", "country"),
]
CL_L4 = [
    cl("Three key chance ideas for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("Sample space = all outcomes for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("Coin = {H, T} for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("Die = 1 to 6 for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("0 ≤ P ≤ 1 for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("Equal likely: 1/n for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("P = 0: impossible for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("P = 1: certain for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("100 × 0.5 = 50 for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("1/6 for any face for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("60 × 1/6 = 10 for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("Equal P each for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
]
CL_L5 = [
    cl("Three key chance ideas for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("Sample space sets up probability for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("Two equally likely outcomes for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("Six equally likely outcomes for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("0 to 1 covers all chance for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("Expected = P × trials for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("Random variation for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("Zero chance = impossible for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("P = 1: certain for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("60 ÷ 6 = 10 for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("Idealisation works in practice for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("Fractions show ratios for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
]

build(SK, OUT, {"L2": (TF_L2, MC_L2, CL_L2), "L3": (TF_L3, MC_L3, CL_L3), "L4": (TF_L4, MC_L4, CL_L4), "L5": ([], MC_L5, CL_L5)})
