#!/usr/bin/env python3
"""Y7 P02 — many trials get closer to expected probabilities; using technology to simulate."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))
from _build_lib_y7 import build, cl

ROOT = Path("/Users/jirrahmacarthur/Claude Cowork access/Kulin Nation Curriculum")
SK = ROOT / "questions/level-07/Mathematics/VC2M7P02.skeleton.json"
OUT = ROOT / "questions/level-07/Mathematics/VC2M7P02.json"

TF_L2 = [
    ("Running many trials gives results closer to the expected probability.", True, "More trials → closer."),
    ("This is sometimes called the law of large numbers.", True, "Law of large numbers."),
    ("Technology can simulate many trials quickly.", True, "Tech speeds simulation."),
    ("A spreadsheet can generate many random tosses or rolls.", True, "Spreadsheets simulate."),
    ("Simulating 1000 coin tosses gives more reliable results than 10.", True, "More trials = more reliable."),
    ("Running few trials always matches the expected probability exactly.", False, "Fewer trials vary more."),
    ("The law of large numbers means each toss is the same.", False, "It's about long-run averages."),
    ("Technology cannot simulate any random experiments.", False, "Tech is widely used."),
    ("A spreadsheet cannot generate random numbers.", False, "Random is built in."),
    ("Simulating 10 tosses is more reliable than 1000.", False, "1000 is more reliable."),
    ("Real coin tosses never show any streaks at all.", False, "Streaks happen and level out."),
    ("Large simulations cannot estimate any hard-to-calculate probabilities.", False, "Simulations help estimation."),
]
TF_L3 = [
    ("After 1000 fair coin tosses, results should be close to 500 heads.", True, "1000 × 0.5 = 500."),
    ("Computers use random number generators to simulate experiments.", True, "RNGs simulate."),
    ("Simulation gives an estimate of probability that improves with more trials.", True, "More trials, better estimate."),
    ("After 1000 fair coin tosses, results should be exactly 500 heads.", False, "Close to, not exactly."),
    ("Computers cannot simulate any chance experiments.", False, "They simulate widely."),
    ("Simulation always gives the exact theoretical probability.", False, "It estimates only."),
    ("Only spreadsheets can simulate chance experiments, not code.", False, "Both work for simulation."),
    ("Real-world probabilities can never be estimated by simulation.", False, "Often estimated this way."),
]
TF_L4 = [
    ("More trials give results closer to expected probabilities, and technology helps simulate quickly.", True, "More trials, more reliable."),
    ("Simulation has no use in studying probability.", False, "Used widely."),
]

MC_L2 = [
    ("What happens when we run many trials?",
     "Results get closer to the expected theoretical probability today",
     "More trials → closer.",
     ["Results get further from the expected probability today", "Results stay exactly the same as one trial today"]),
    ("What is this principle called?",
     "The law of large numbers, applied across many trials today",
     "Law of large numbers.",
     ["The law of small numbers in any case today", "The law of single trials in any case today"]),
    ("How can technology help with probability?",
     "It can simulate many trials quickly using random number generators today",
     "Tech speeds simulation.",
     ["Technology cannot simulate any experiments today", "Technology only works for certain experiments today"]),
    ("How can a spreadsheet simulate?",
     "It can generate many random tosses or rolls automatically today",
     "Spreadsheets simulate.",
     ["Spreadsheets cannot generate random numbers today", "Only special calculators can simulate today"]),
    ("Why is 1000 simulated tosses more reliable than 10?",
     "More trials reduce random variation around the expected value today",
     "More trials = more reliable.",
     ["Fewer trials are always more reliable today", "Number of trials never affects reliability today"]),
    ("Do streaks in real coin tosses last forever?",
     "No, streaks level out over many tosses by the law of large numbers today",
     "Streaks level out.",
     ["Yes, streaks last for any number of trials today", "Streaks never appear in fair coin tosses today"]),
    ("How can simulation help estimate hard probabilities?",
     "Many trials give an estimate of probabilities hard to calculate directly today",
     "Simulations estimate.",
     ["Simulation gives the exact theoretical probability today", "Simulation only confirms calculations today"]),
    ("How many heads do we expect from 1000 fair coin tosses?",
     "About five hundred heads, since one thousand times 0.5 equals 500 today",
     "About 500 heads.",
     ["About one thousand heads in this case today", "About zero heads in this case today"]),
    ("What do computers use to simulate experiments?",
     "Random number generators that produce random outcomes today",
     "RNGs simulate.",
     ["Pre-set fixed numbers for every simulation today", "Only one number for every simulation today"]),
    ("Does simulation give the exact theoretical probability?",
     "No, it gives an estimate that improves with more trials today",
     "Estimate, not exact.",
     ["Yes, simulation gives the exact probability always today", "Only with very few trials does simulation give exact today"]),
    ("Can both spreadsheets and code simulate?",
     "Yes, both spreadsheets and code can simulate chance experiments today",
     "Both work for simulation.",
     ["Only code can simulate today", "Only spreadsheets can simulate today"]),
    ("Can real-world probabilities be estimated by simulation?",
     "Yes, complex real-world probabilities are often estimated this way today",
     "Often estimated by simulation.",
     ["No, simulation cannot estimate real probabilities today", "Only theoretical probabilities are estimated this way today"]),
]
MC_L3 = [
    ("Why do many trials give closer results to expected?",
     "Random variation averages out as the number of trials grows today",
     "Variation averages out.",
     ["Variation grows as trials increase today", "Trials never affect the result today"]),
    ("Why is this called the law of large numbers?",
     "Long-run averages converge to expected values as trials grow today",
     "Long-run convergence.",
     ["It applies only to small numbers of trials today", "It is a law about single trials today"]),
    ("Why does technology speed up simulation?",
     "Computers can do thousands of trials in seconds today",
     "Computers are fast.",
     ["Computers slow down simulation today", "Only humans can simulate experiments today"]),
    ("Why are spreadsheet random functions useful for simulation?",
     "They generate random outcomes that mimic real chance experiments today",
     "Random functions mimic chance.",
     ["Spreadsheets give the same number every time today", "Spreadsheets cannot do simulation today"]),
    ("Why do larger simulations give more reliable estimates?",
     "More trials reduce random variation around the expected value today",
     "More trials = more reliable.",
     ["Fewer trials are always more reliable today", "Number of trials does not affect reliability today"]),
    ("Why do streaks happen in fair coin tosses?",
     "Random outcomes can cluster by chance in any short run today",
     "Random clustering.",
     ["Coins are not fair when streaks happen today", "Streaks mean the law of large numbers fails today"]),
    ("Why does simulation help with hard probabilities?",
     "Many trials give an estimate of probabilities hard to calculate directly today",
     "Simulations estimate hard cases.",
     ["Simulation gives exact answers always today", "Simulation only works for easy cases today"]),
    ("Why does 1000 tosses give about 500 heads?",
     "1000 trials with P = 0.5 give expected count 500 today",
     "1000 × 0.5 = 500.",
     ["1000 tosses give exactly 1000 heads today", "1000 tosses give exactly 0 heads today"]),
    ("Why are random number generators central to simulation?",
     "They mimic the unpredictability of real chance experiments today",
     "Mimic real randomness.",
     ["Random number generators give fixed numbers today", "Random number generators are unrelated to simulation today"]),
    ("Why does simulation give an estimate not the exact probability?",
     "Random variation in trials means the result is approximate today",
     "Random variation = approximate.",
     ["Simulation always gives the exact value today", "Simulation never gives any answer today"]),
    ("Why are simulations widely used in industry and research?",
     "They estimate probabilities for problems too complex for direct calculation today",
     "Used for complex estimates.",
     ["Simulations are only used in school today", "Simulations have no industry use today"]),
    ("Why is identifying the question important before simulating?",
     "It tells us what to count and how many trials to run today",
     "Question shapes simulation.",
     ["Questions are unimportant in simulation today", "Simulation works without any question today"]),
]
MC_L4 = [
    ("Which best explains many trials and simulation?",
     "More trials give results closer to expected probabilities, and technology speeds it up today",
     "More trials, more reliable.",
     ["Simulation has no use today", "More trials give worse results today"]),
    ("Why do many trials give closer results?",
     "Random variation averages out as the number of trials grows today",
     "Variation averages out.",
     ["Variation grows as trials increase today", "Trials never affect the result today"]),
    ("Why is this the law of large numbers?",
     "Long-run averages converge to expected values as trials grow today",
     "Long-run convergence.",
     ["It applies only to small numbers of trials today", "It is a law about single trials today"]),
    ("Why does technology speed up simulation?",
     "Computers can do thousands of trials in seconds today",
     "Computers are fast.",
     ["Computers slow down simulation today", "Only humans can simulate today"]),
    ("Why are spreadsheet random functions useful?",
     "They generate random outcomes that mimic real chance experiments today",
     "Random functions mimic chance.",
     ["Spreadsheets give the same number every time today", "Spreadsheets cannot simulate today"]),
    ("Why do larger simulations give more reliable estimates?",
     "More trials reduce random variation around the expected value today",
     "More trials = more reliable.",
     ["Fewer trials are always more reliable today", "Trials do not affect reliability today"]),
    ("Why do streaks happen in fair coin tosses?",
     "Random outcomes can cluster by chance in any short run today",
     "Random clustering.",
     ["Coins are not fair when streaks happen today", "Streaks mean law of large numbers fails today"]),
    ("Why does simulation help with hard probabilities?",
     "Many trials give an estimate of probabilities hard to calculate directly today",
     "Simulations estimate hard cases.",
     ["Simulation gives exact answers always today", "Simulation only works for easy cases today"]),
    ("Why does 1000 tosses give about 500 heads?",
     "1000 trials with P = 0.5 give expected count 500 today",
     "1000 × 0.5 = 500.",
     ["1000 tosses give exactly 1000 heads today", "1000 tosses give exactly 0 heads today"]),
    ("Why are RNGs central to simulation?",
     "They mimic the unpredictability of real chance experiments today",
     "Mimic real randomness.",
     ["RNGs give fixed numbers today", "RNGs are unrelated to simulation today"]),
    ("Why does simulation give an estimate not exact value?",
     "Random variation in trials means the result is approximate today",
     "Random variation = approximate.",
     ["Simulation always gives exact value today", "Simulation never gives any answer today"]),
    ("Why are simulations widely used?",
     "They estimate probabilities for problems too complex for direct calculation today",
     "Used for complex estimates.",
     ["Simulations are only used in school today", "Simulations have no industry use today"]),
]
MC_L5 = [
    ("Evaluate: how do many trials and tech support probability?",
     "More trials give results closer to expected probabilities, and tech speeds it up today",
     "More trials, more reliable.",
     ["Simulation has no use today", "More trials give worse results today"]),
    ("Justify: why do many trials give closer results?",
     "Random variation averages out as the number of trials grows today",
     "Variation averages out.",
     ["Variation grows as trials increase today", "Trials never affect the result today"]),
    ("Assess: when does the law of large numbers most apply?",
     "When the number of trials grows large and averages converge today",
     "Long-run convergence.",
     ["When the number of trials is one or two today", "When trials never grow large today"]),
    ("Critique: a risk of judging fairness from few trials is what?",
     "Few trials show high variation and may mislead about long-run probability today",
     "Few trials mislead.",
     ["Few trials always give the right answer today", "Trials never affect judgement today"]),
    ("Evaluate: how does technology speed simulation?",
     "Computers can do thousands of trials in seconds today",
     "Computers are fast.",
     ["Computers slow down simulation today", "Only humans can simulate today"]),
    ("Justify: why do larger simulations give better estimates?",
     "More trials reduce random variation around the expected value today",
     "More trials = more reliable.",
     ["Fewer trials are always more reliable today", "Trials do not affect reliability today"]),
    ("Assess: when do streaks most appear in fair experiments?",
     "When random outcomes cluster by chance in short runs today",
     "Random clustering in short runs.",
     ["When coins are unfair always today", "When law of large numbers fails today"]),
    ("Critique: a risk of treating simulation as exact is what?",
     "Simulation gives estimates that vary; not exact theoretical probabilities today",
     "Estimate, not exact.",
     ["Simulation always gives exact value today", "Simulation never gives answer today"]),
    ("Evaluate: how does 1000 tosses give ~500 heads?",
     "1000 trials with P = 0.5 give expected count 500 today",
     "1000 × 0.5 = 500.",
     ["1000 tosses give exactly 1000 heads today", "1000 tosses give exactly 0 heads today"]),
    ("Justify: why are RNGs the core of simulation?",
     "They mimic the unpredictability of real chance experiments today",
     "Mimic real randomness.",
     ["RNGs give fixed numbers today", "RNGs are unrelated to simulation today"]),
    ("Assess: when do simulations most help in industry?",
     "When estimating probabilities for problems too complex to calculate directly today",
     "Used for complex estimates.",
     ["Simulations only work in school today", "Simulations have no industry use today"]),
    ("Critique: a risk of running too few trials is what?",
     "Results vary widely and do not converge to the expected value today",
     "Few trials = high variation.",
     ["Few trials always give exact answers today", "Trials never affect convergence today"]),
    ("Evaluate: how do simulations support complex probability questions?",
     "They estimate probabilities for problems too complex for direct calculation today",
     "Used for complex estimates.",
     ["Simulations only work for school problems today", "Simulations have no use today"]),
    ("Justify: why is identifying the question first important?",
     "It tells us what to count and how many trials to run today",
     "Question shapes simulation.",
     ["Questions are unimportant in simulation today", "Simulation works without any question today"]),
]
CL_L2 = [
    cl("Running many trials gives results closer to the expected {{blank:1}} for the {{blank:2}}.", "probability", "country"),
    cl("This is sometimes called the law of large {{blank:1}} for the {{blank:2}}.", "numbers", "country"),
]
CL_L3 = [
    cl("Technology can simulate many trials {{blank:1}} for the {{blank:2}}.", "quickly", "country"),
    cl("A spreadsheet can generate many random tosses or {{blank:1}} for the {{blank:2}}.", "rolls", "country"),
    cl("Simulating 1000 coin tosses gives more reliable results than {{blank:1}} for the {{blank:2}}.", "10", "country"),
    cl("After 1000 fair coin tosses, results should be close to {{blank:1}} heads for the {{blank:2}}.", "500", "country"),
    cl("Computers use random number generators to simulate {{blank:1}} for the {{blank:2}}.", "experiments", "country"),
    cl("Simulation gives an estimate of probability that improves with more {{blank:1}} for the {{blank:2}}.", "trials", "country"),
]
CL_L4 = [
    cl("More trials, more reliable for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("More trials → closer for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("Law of large numbers for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("Tech speeds simulation for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("Spreadsheets simulate for the {{blank:1}} and the {{blank:2}}.", "country", "tech"),
    cl("More trials = more reliable for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("Streaks level out for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("Simulations help estimation for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("1000 × 0.5 = 500 for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("RNGs simulate for the {{blank:1}} and the {{blank:2}}.", "country", "tech"),
    cl("More trials, better estimate for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("Both work for simulation for the {{blank:1}} and the {{blank:2}}.", "country", "tech"),
]
CL_L5 = [
    cl("More trials, more reliable for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("Variation averages out for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("Long-run convergence for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("Few trials mislead for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("Computers are fast for the {{blank:1}} and the {{blank:2}}.", "country", "tech"),
    cl("More trials = more reliable for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("Random clustering in short runs for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("Estimate, not exact for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("1000 × 0.5 = 500 for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("Mimic real randomness for the {{blank:1}} and the {{blank:2}}.", "country", "tech"),
    cl("Used for complex estimates for the {{blank:1}} and the {{blank:2}}.", "country", "industry"),
    cl("Few trials = high variation for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
]

build(SK, OUT, {"L2": (TF_L2, MC_L2, CL_L2), "L3": (TF_L3, MC_L3, CL_L3), "L4": (TF_L4, MC_L4, CL_L4), "L5": ([], MC_L5, CL_L5)})
