#!/usr/bin/env python3
"""Y7 N10 — mathematical modelling with rational numbers and percentages."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))
from _build_lib_y7 import build, cl

ROOT = Path("/Users/jirrahmacarthur/Claude Cowork access/Kulin Nation Curriculum")
SK = ROOT / "questions/level-07/Mathematics/VC2M7N10.skeleton.json"
OUT = ROOT / "questions/level-07/Mathematics/VC2M7N10.json"

TF_L2 = [
    ("Mathematical modelling uses maths to solve real-world problems.", True, "Modelling solves real problems."),
    ("Rational numbers include fractions, decimals, and integers.", True, "Rationals include all three."),
    ("Percentages are useful in modelling money problems.", True, "Percent in money."),
    ("A 10% discount on $50 saves $5.", True, "0.10 × 50 = 5."),
    ("A modelling step is to identify the question first.", True, "Identify question first."),
    ("Mathematical modelling never uses real-world data.", False, "It uses real data."),
    ("Rational numbers exclude fractions and decimals.", False, "They include both."),
    ("Percentages are useless in money modelling.", False, "Percentages are central."),
    ("A 10% discount on $50 saves $50.", False, "It saves $5."),
    ("A modelling step is to ignore the question entirely.", False, "Identify it first."),
    ("Estimation always replaces the modelling calculation.", False, "Estimation checks, not replaces."),
    ("Modelling never uses estimation.", False, "It often uses estimation."),
]
TF_L3 = [
    ("Adding 15% GST to $80 gives $92.", True, "$80 × 1.15 = $92."),
    ("Sharing $60 in the ratio 2:1 gives $40 and $20.", True, "Ratio sharing."),
    ("A 25% discount on $200 saves $50.", True, "0.25 × 200 = 50."),
    ("Adding 15% GST to $80 gives $95.", False, "It gives $92."),
    ("Sharing $60 in the ratio 2:1 gives $30 and $30.", False, "It gives $40 and $20."),
    ("A 25% discount on $200 saves $25.", False, "It saves $50."),
    ("Modelling never involves identifying given information or choosing operations.", False, "Both are key steps."),
    ("Real-world problems can never be modelled with maths.", False, "Many can be modelled."),
]
TF_L4 = [
    ("Mathematical modelling with rationals and percentages solves practical real-world problems.", True, "Modelling solves real problems."),
    ("Modelling has no use beyond school maths.", False, "Used widely."),
]

MC_L2 = [
    ("What is mathematical modelling?",
     "Using maths to represent and solve real-world problems today",
     "Modelling solves real problems.",
     ["Using maths only on imaginary problems today", "Using maths to make problems more confusing today"]),
    ("What numbers count as rational?",
     "Fractions, decimals, and integers all count as rational numbers today",
     "Rationals include all three.",
     ["Only fractions count as rational numbers today", "Only integers count as rational numbers today"]),
    ("Why are percentages useful in money problems?",
     "Discounts, taxes, and interest are commonly given as percentages today",
     "Money uses percentages.",
     ["Money never uses percentages today", "Percentages are useless in money today"]),
    ("How much does a 10% discount on $50 save?",
     "Ten percent of fifty dollars equals five dollars saved today",
     "$5 saved.",
     ["Ten percent of fifty dollars equals fifty dollars saved today", "Ten percent of fifty dollars equals 0.5 dollars today"]),
    ("What is the first step in modelling?",
     "Identify the question and what is being asked today",
     "Identify question first.",
     ["Skip the question and start calculating today", "Choose any operation without reading the question today"]),
    ("How does estimation help modelling?",
     "It checks the answer is reasonable before reporting today",
     "Estimation checks.",
     ["Estimation gives the exact answer today", "Estimation slows down the modelling process today"]),
    ("How much is $80 with 15% GST added?",
     "Multiply 80 by 1.15 to get 92 dollars total today",
     "$80 × 1.15 = $92.",
     ["Multiply 80 by 0.15 to get 12 dollars total today", "Multiply 80 by 15 to get 1200 dollars total today"]),
    ("How do we share $60 in the ratio 2:1?",
     "Three parts of $20: two parts give $40, one part gives $20 today",
     "$40 and $20.",
     ["Half each: $30 and $30 today", "Whole amount to one side: $60 and $0 today"]),
    ("How much does a 25% discount on $200 save?",
     "Twenty-five percent of $200 equals $50 saved today",
     "$50 saved.",
     ["Twenty-five percent of $200 equals $25 saved today", "Twenty-five percent of $200 equals $200 saved today"]),
    ("What is a key modelling step besides identifying the question?",
     "Choose the right operations and check the answer is reasonable today",
     "Choose operations and check.",
     ["Use any random operation without thinking today", "Skip checking the answer entirely today"]),
    ("Are real-world problems modellable with maths?",
     "Yes, many real-world problems can be modelled with rationals today",
     "Many can be modelled.",
     ["No, real-world problems cannot be modelled today", "Only school problems can be modelled today"]),
    ("Where is rational arithmetic used in real life?",
     "Money, recipes, measurements, and many everyday tasks today",
     "Used in money and recipes.",
     ["Only in school maths classes today", "Nowhere outside specialised work today"]),
]
MC_L3 = [
    ("Why is identifying the question the first modelling step?",
     "If we do not know what is asked, we cannot choose the right operations today",
     "Question shapes choice.",
     ["The question is unimportant in modelling today", "We can choose operations without the question today"]),
    ("Why are percentages central in money problems?",
     "Discounts, taxes, and interest are commonly given as percentages today",
     "Money uses percentages widely.",
     ["Money never uses percentages today", "Percentages are useless in money today"]),
    ("Why does a 10% discount on $50 save $5?",
     "Ten percent of fifty equals five in this calculation today",
     "0.10 × 50 = 5.",
     ["Ten percent of fifty equals fifty today", "Ten percent of fifty equals 0.5 today"]),
    ("Why does $80 with 15% GST become $92?",
     "Adding 15% means multiplying by 1.15, and 80 × 1.15 = 92 today",
     "× 1.15 to add 15%.",
     ["Multiply by 0.15 to add 15% today", "Multiply by 15 to add 15% today"]),
    ("Why does sharing $60 in 2:1 give $40 and $20?",
     "Three parts total: $60 ÷ 3 = $20 per part; 2 parts = $40 today",
     "$60 ÷ 3 = $20 per part.",
     ["Sharing in any ratio gives equal halves today", "Sharing in 2:1 gives $30 and $30 today"]),
    ("Why does estimation strengthen modelling?",
     "It catches large errors before reporting the final answer today",
     "Estimation catches errors.",
     ["Estimation introduces new errors today", "Estimation is slow and unhelpful today"]),
    ("Why are checks at the end of modelling important?",
     "They confirm the answer is reasonable for the original question today",
     "Checks confirm reasonableness.",
     ["Checks have no role in modelling today", "Checking answers slows the work today"]),
    ("Why is choosing the right operations central to modelling?",
     "Different problems need different operations to find the right answer today",
     "Right operation for the problem.",
     ["All problems use the same operation today", "Operation choice never affects the answer today"]),
    ("Why is rational arithmetic the basis of many models?",
     "Rationals cover whole numbers, fractions, and decimals used in real problems today",
     "Rationals cover real values.",
     ["Rationals only appear in school maths today", "Rationals are unrelated to real problems today"]),
    ("Why are percentages useful for comparisons in modelling?",
     "They put values on a common base of 100 for easy comparison today",
     "Common base of 100.",
     ["They put values on different bases today", "They have no role in comparison today"]),
    ("Why does modelling sometimes need rounding?",
     "Real-world quantities like money round to two decimal places today",
     "Money rounds to 2 decimals.",
     ["Modelling never uses rounding today", "Rounding always gives wrong answers today"]),
    ("Why is identifying given information important?",
     "It tells us what we already know to use in calculations today",
     "Given info is used as input.",
     ["Given information has no use in modelling today", "Given information is always irrelevant today"]),
]
MC_L4 = [
    ("Which best explains modelling with rationals and percentages?",
     "It uses rationals and percentages to solve practical real-world problems today",
     "Modelling solves real problems.",
     ["Modelling never uses these tools today", "Modelling has no use today"]),
    ("Why is identifying the question first?",
     "If we do not know what is asked, we cannot choose the right operations today",
     "Question shapes choice.",
     ["The question is unimportant in modelling today", "We can choose without the question today"]),
    ("Why are percentages central in money problems?",
     "Discounts, taxes, and interest are commonly given as percentages today",
     "Money uses percentages widely.",
     ["Money never uses percentages today", "Percentages are useless in money today"]),
    ("Why does a 10% discount on $50 save $5?",
     "Ten percent of fifty equals five in this calculation today",
     "0.10 × 50 = 5.",
     ["Ten percent of fifty equals fifty today", "Ten percent of fifty equals 0.5 today"]),
    ("Why does $80 with 15% GST become $92?",
     "Adding 15% means multiplying by 1.15, and 80 × 1.15 = 92 today",
     "× 1.15 to add 15%.",
     ["Multiply by 0.15 to add 15% today", "Multiply by 15 to add 15% today"]),
    ("Why does sharing $60 in 2:1 give $40 and $20?",
     "Three parts total: $60 ÷ 3 = $20 per part; 2 parts = $40 today",
     "$60 ÷ 3 = $20 per part.",
     ["Sharing in any ratio gives equal halves today", "Sharing in 2:1 gives $30 and $30 today"]),
    ("Why does estimation strengthen modelling?",
     "It catches large errors before reporting the final answer today",
     "Estimation catches errors.",
     ["Estimation introduces new errors today", "Estimation is slow and unhelpful today"]),
    ("Why are checks at the end important?",
     "They confirm the answer is reasonable for the original question today",
     "Checks confirm reasonableness.",
     ["Checks have no role in modelling today", "Checking slows the work today"]),
    ("Why is choosing the right operation key?",
     "Different problems need different operations to find the right answer today",
     "Right operation for the problem.",
     ["All problems use the same operation today", "Operation choice never affects answer today"]),
    ("Why are rationals the basis of many models?",
     "Rationals cover whole numbers, fractions, and decimals used in real problems today",
     "Rationals cover real values.",
     ["Rationals only appear in school maths today", "Rationals are unrelated to real problems today"]),
    ("Why does modelling sometimes need rounding?",
     "Real-world quantities like money round to two decimal places today",
     "Money rounds to 2 decimals.",
     ["Modelling never uses rounding today", "Rounding always gives wrong answers today"]),
    ("Why is identifying given information important?",
     "It tells us what we already know to use in calculations today",
     "Given info is used as input.",
     ["Given information has no use today", "Given information is always irrelevant today"]),
]
MC_L5 = [
    ("Evaluate: how does modelling solve real problems?",
     "It uses rationals and percentages to solve practical real-world problems today",
     "Modelling solves real problems.",
     ["Modelling never uses these tools today", "Modelling has no use today"]),
    ("Justify: why is identifying the question first?",
     "If we do not know what is asked, we cannot choose the right operations today",
     "Question shapes choice.",
     ["The question is unimportant today", "We can choose without the question today"]),
    ("Assess: when do percentages most clearly help money problems?",
     "When discounts, taxes, and interest need to be calculated today",
     "Money uses percentages widely.",
     ["When money never uses percentages today", "When percentages are useless today"]),
    ("Critique: a risk of skipping the check step is what?",
     "Errors can pass without confirmation that the answer makes sense today",
     "Checks catch errors.",
     ["Checks always introduce new errors today", "Skipping checks improves the answer today"]),
    ("Evaluate: how does sharing $60 in 2:1 work?",
     "Three parts total: $60 ÷ 3 = $20 per part; 2 parts = $40 today",
     "$60 ÷ 3 = $20 per part.",
     ["Sharing in any ratio gives equal halves today", "Sharing in 2:1 gives $30 and $30 today"]),
    ("Justify: why does $80 with 15% GST = $92?",
     "Adding 15% means multiplying by 1.15, and 80 × 1.15 = 92 today",
     "× 1.15 to add 15%.",
     ["Multiply by 0.15 to add 15% today", "Multiply by 15 to add 15% today"]),
    ("Assess: when does estimation most help modelling?",
     "When it catches large errors before reporting a final answer today",
     "Estimation catches errors.",
     ["Estimation introduces new errors today", "Estimation is slow and unhelpful today"]),
    ("Critique: a risk of choosing the wrong operation is what?",
     "Different problems need different operations; the wrong one gives a wrong answer today",
     "Right operation for the problem.",
     ["All problems use the same operation today", "Operation choice never affects answer today"]),
    ("Evaluate: how do rationals support real-world models?",
     "They cover whole numbers, fractions, and decimals used in real problems today",
     "Rationals cover real values.",
     ["Rationals only appear in school maths today", "Rationals are unrelated to real problems today"]),
    ("Justify: why is rounding sometimes needed in modelling?",
     "Real-world quantities like money round to two decimal places today",
     "Money rounds to 2 decimals.",
     ["Modelling never uses rounding today", "Rounding always gives wrong answers today"]),
    ("Assess: when does identifying given information matter most?",
     "When the calculation depends on what we already know today",
     "Given info is used as input.",
     ["Given information has no use today", "Given information is always irrelevant today"]),
    ("Critique: a risk of treating modelling as recipe-following is what?",
     "It can miss the unique features of each real problem today",
     "Each problem has unique features.",
     ["All problems are exactly the same today", "Recipe-following always works perfectly today"]),
    ("Evaluate: how do First Nations resource sharing patterns model rationals?",
     "Sharing food and resources uses rational ratios in many traditional patterns today",
     "Sharing patterns use rationals.",
     ["First Nations sharing never uses maths today", "Sharing uses no proportional reasoning today"]),
    ("Justify: why is checking the answer central?",
     "Confirming reasonableness catches errors and supports trust in the result today",
     "Checking supports trust.",
     ["Checking is never necessary today", "Checking always introduces errors today"]),
]
CL_L2 = [
    cl("Mathematical modelling uses maths to solve real-world {{blank:1}} for the {{blank:2}}.", "problems", "country"),
    cl("Rational numbers include fractions, decimals, and {{blank:1}} for the {{blank:2}}.", "integers", "country"),
]
CL_L3 = [
    cl("Percentages are useful in modelling money {{blank:1}} for the {{blank:2}}.", "problems", "country"),
    cl("A 10% discount on $50 saves ${{blank:1}} for the {{blank:2}}.", "5", "country"),
    cl("A modelling step is to identify the question {{blank:1}} for the {{blank:2}}.", "first", "country"),
    cl("Adding 15% GST to $80 gives ${{blank:1}} for the {{blank:2}}.", "92", "country"),
    cl("Sharing $60 in the ratio 2:1 gives $40 and ${{blank:1}} for the {{blank:2}}.", "20", "country"),
    cl("A 25% discount on $200 saves ${{blank:1}} for the {{blank:2}}.", "50", "country"),
]
CL_L4 = [
    cl("Modelling solves real problems for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("Modelling solves real problems for the {{blank:1}} and the {{blank:2}}.", "country", "real life"),
    cl("Rationals include all three for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("Percent in money for the {{blank:1}} and the {{blank:2}}.", "country", "money"),
    cl("0.10 × 50 = 5 for the {{blank:1}} and the {{blank:2}}.", "country", "money"),
    cl("Identify question first for the {{blank:1}} and the {{blank:2}}.", "country", "modelling"),
    cl("Estimation checks for the {{blank:1}} and the {{blank:2}}.", "country", "modelling"),
    cl("$80 × 1.15 = $92 for the {{blank:1}} and the {{blank:2}}.", "country", "money"),
    cl("Ratio sharing for the {{blank:1}} and the {{blank:2}}.", "country", "money"),
    cl("0.25 × 200 = 50 for the {{blank:1}} and the {{blank:2}}.", "country", "money"),
    cl("Two key modelling steps for the {{blank:1}} and the {{blank:2}}.", "country", "modelling"),
    cl("Many can be modelled for the {{blank:1}} and the {{blank:2}}.", "country", "modelling"),
]
CL_L5 = [
    cl("Modelling solves real problems for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("Question shapes choice for the {{blank:1}} and the {{blank:2}}.", "country", "modelling"),
    cl("Money uses percentages widely for the {{blank:1}} and the {{blank:2}}.", "country", "money"),
    cl("Checks catch errors for the {{blank:1}} and the {{blank:2}}.", "country", "modelling"),
    cl("$60 ÷ 3 = $20 per part for the {{blank:1}} and the {{blank:2}}.", "country", "money"),
    cl("× 1.15 to add 15% for the {{blank:1}} and the {{blank:2}}.", "country", "money"),
    cl("Estimation catches errors for the {{blank:1}} and the {{blank:2}}.", "country", "modelling"),
    cl("Right operation for the problem for the {{blank:1}} and the {{blank:2}}.", "country", "modelling"),
    cl("Rationals cover real values for the {{blank:1}} and the {{blank:2}}.", "country", "maths"),
    cl("Money rounds to 2 decimals for the {{blank:1}} and the {{blank:2}}.", "country", "money"),
    cl("Given info is used as input for the {{blank:1}} and the {{blank:2}}.", "country", "modelling"),
    cl("Sharing patterns use rationals for the {{blank:1}} and the {{blank:2}}.", "First Nations", "country"),
]

build(SK, OUT, {"L2": (TF_L2, MC_L2, CL_L2), "L3": (TF_L3, MC_L3, CL_L3), "L4": (TF_L4, MC_L4, CL_L4), "L5": ([], MC_L5, CL_L5)})
